services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PhpLogger
      MYSQL_DATABASE: php_logger
      MYSQL_USER: user_phplogger
      MYSQL_PASSWORD: PhpLogger
    ports:
      - "3307:3306"
    networks:
      logger_network:
        ipv4_address: 10.0.0.2
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      logger_network:
        ipv4_address: 10.0.0.3

volumes:
  mysql-data:

networks:
  logger_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16