version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: php-logger-debug
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PhpLogger
      MYSQL_DATABASE: php_logger
      MYSQL_USER: user_phplogger
      MYSQL_PASSWORD: PhpLogger
    ports:
      - "8081:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: php:8.2-apache
    container_name: php_logger-app
    working_dir: /var/www/html
    volumes:
     - ../:/var/www/html
     - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
     - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
     - db
    ports:
     - "3500:80"
    command: >
     /bin/bash -c "php artisan key:generate &&
                    php artisan migrate --force &&
                    apache2-foreground"

volumes:
  mysql-data: